apiVersion: v1
kind: Namespace
metadata:
  name: mynamespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: mynamespace
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ork25/nginx:latest 
        ports:
        - containerPort: 443
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi" 

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: mynamespace
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
  namespace: mynamespace
spec:
  selector:
    matchLabels:
      app: redis-cache
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-cache
    spec:
      containers:
      - name: redis
        image: ork25/redis:latest 
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi" 

---

apiVersion: v1
kind: Service
metadata:
  name: redis-cache
  namespace: mynamespace
spec:
  selector:
    app: redis-cache
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: mynamespace
spec:
  selector:
    matchLabels:
      app: orders
  replicas: 1
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: ork25/orders:latest 
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_DB
          value: order
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: user
        resources:
          limits:
            cpu: "1" 
            memory: "1Gi"

---

apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: mynamespace
spec:
  selector:
    app: orders
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: mynamespace
spec:
  selector:
    matchLabels:
      app: cart
  replicas: 1
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: ork25/cart:latest  
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_DB
          value: order
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: user
        resources:
          limits:
            cpu: "1"
            memory: "1Gi" 

---

apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: mynamespace
spec:
  selector:
    app: cart
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
