version: "3"

services:
  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true

volumes:
  rabbitmq_data:
