# Use an official RabbitMQ image as the base image
FROM rabbitmq:3-management

# Set environment variables
ENV RABBITMQ_DEFAULT_USER=user
ENV RABBITMQ_DEFAULT_PASS=password

# Expose ports for RabbitMQ and RabbitMQ Management Plugin
EXPOSE 5672 15672
