version: "3"

services:
  flask-app:
    container_name: flask-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_DB=order
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    depends_on:
      - postgres
    networks:
      - proxy-net

  postgres:
    container_name: postgres
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=order
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    ports:
      - "54320:5432"
    volumes:
      - pgdb:/var/lib/postgresql/data
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true

volumes:
  pgdb: {}
