version: "3"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Password.2510
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    ports:
      - "1433:1433"
