version: "3.4"

services:
  graphqlgateway:
    image: graphqlgateway
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
