version: "3.4"

services:
  graphqlgateway:
    image: graphqlgateway
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - 8000:8000
      - 9229:9229
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
