version: "3.4"

services:
  products:
    container_name: "services"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: products
    environment:
      NODE_ENV: development
    ports:
      - "5000:5000"
      - "5001:5000"
    depends_on:
      - db
    networks:
      - proxy-net

  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products
    volumes:
      - /var/lib/docker/volumes/mysql/_data
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
