version: "3.8"

services:
  java_app:
    container_name: java_app
    image: ork/java_app:1.0.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/mydatabase
      - DATABASE_USERNAME=myuser
      - DATABASE_PASSWORD=secret
    depends_on:
      - postgres

  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
