version: "3"

services:
  load_balancer:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx-load-balancer.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
