# Use the official NGINX image as the base image
FROM nginx:latest

# Copy your NGINX configuration file for the API gateway
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the necessary ports
EXPOSE 8000

# Start NGINX when the container starts
CMD ["nginx", "-g", "daemon off;"]

