version: "3"

services:
  payment_api:
    build: .
    ports:
      - "80:80"
    networks:
      - proxy-net
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - MARIADB_USER=myuser
      - MARIADB_PASSWORD=mypassword
      - MARIADB_DATABASE=payments

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_USER=myuser
      - MARIADB_PASSWORD=mypassword
      - MARIADB_DATABASE=payments
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
